# Generated by Django 4.2.5 on 2023-09-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=255)),
                ('actions', models.CharField(max_length=255)),
                ('transaction_type', models.CharField(max_length=255)),
                ('symbol', models.CharField(max_length=255)),
                ('quantity', models.IntegerField()),
                ('type', models.CharField(max_length=255)),
                ('price_status', models.DecimalField(decimal_places=4, max_digits=10)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=5)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
