# Generated by Django 4.2.5 on 2023-09-17 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_connector_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Trade',
            new_name='Transaction',
        ),
    ]
